import Head from "next/head"
const about = () => {
    return (
        <div>
        <Head>
        <title>Acerca de</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            Esta es la pagina acerca de...
        </div>
    )
}

export default about